# Project
version=2.7.1.0+fabric
group=com.github.alexthe666.citadel
# Common
minecraft_version=1.21.1
mod_name=Citadel
mod_author=Alexthe666, BluSpring
mod_id=citadel
license=GNU LESSER GENERAL PUBLIC LICENSE
credits=Gegy1000
description=A shared code library for many of Alexthe666's mods. Code used from LLibrary with permission.
minecraft_version_range=>=1.21 <=1.21.1
# Fabric
loader_version=0.19.5
fabric_version=0.116.17+1.21.1
parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17
porting_lib_version = 3.1.0-beta.91+1.21.1
# Gradle
systemProp.org.gradle.internal.http.connectionTimeout=180000
systemProp.org.gradle.internal.http.socketTimeout=180000
org.gradle.jvmargs=-Xmx3G